#!/bin/sh
PHPTOOLS_CONTAINER_NAME=`docker ps --format "{{.Names}}" | grep php-tools`
MYSQL_CONTAINER_NAME=`docker ps --format "{{.Names}}" | grep mysql`
alias php="docker exec -t $PHPTOOLS_CONTAINER_NAME php $@"
alias magerun="docker exec -ti $PHPTOOLS_CONTAINER_NAME magerun $@"
alias composer="docker exec -ti $PHPTOOLS_CONTAINER_NAME composer -d=../ $@"
alias mysql="docker exec -ti $MYSQL_CONTAINER_NAME mysql $@"
